services:
  node:
    build:
      context: ${NODE_DIR_ABS}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ${XO_ROOT_DIR}/${XO_NODE_ROOT}:/var/www/html/:rw
    working_dir: /var/www/html
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    depends_on:
      php:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s

    env_file:
      - ${XO_ROOT_DIR}/.env
      - ${XO_ROOT_DIR}/.env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["npm", "run", "dev", "--host 0.0.0.0"]
networks:
  default:
    external: true
    name: ${XO_PROJECT_NAME}
